services:
  frontend:
    ports:
      - "3000:3000"

  backend:
    ports:
      - "5000:5000"

  redis:
    ports:
      - "6379:6379"

  mongo:
    ports:
      - "27017:27017"

  mongo-express:
    ports:
      - "8081:8081"
