FROM node:18-alpine

WORKDIR /usr/src/app

# Install dependencies first
COPY backend/package*.json ./
RUN npm install

# Copy backend code
COPY backend/. .

# Ensure entrypoint exists
COPY backend/entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
