FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package files and install deps
COPY frontend/package*.json ./
RUN npm install

# Copy rest of the app
COPY frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
