FROM node:22-alpine

WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/. ./

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start", "--", "-p", "3000", "-H", "0.0.0.0"]